### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by ypypjay** [SlightlyMad/VolumetricLights#4]
Hi,SlightlyMad.
I've been testing this project on a PS4 console.However,there were tons of problems showed up.I managed to handle some of them by converting
**float4 centerColor = _MainTex.Sample(sampler_MainTex,uv);**
into
**float4 centerColor = UNITY_SAMPLE_TEX2D(_MainTex,uv);**.
Solved Problems(Image Below):
![image](https://cloud.githubusercontent.com/assets/5518827/20166927/f31615b8-a752-11e6-899d-dc0221dabf24.png)
But there are still some issues that drive me mad.(Image Below):
![image](https://cloud.githubusercontent.com/assets/5518827/20167034/af9f5816-a753-11e6-8150-d15259edb4bb.png)
I can sense that the problems are caused by PS4 sampler state,sort of.But I can't get any answer or information on the web.
Would you please give me some hints?
Much appreciated.
BTW,sorry for my poor English.(^_^)

**Comment by SlightlyMad** [comment]
Hm, interesting. Looks like you can't use Texture.Sample(sampler, uv) function. That you have to use the old syntax (tex2D(tex, uv)). That's funny because PSSL in PS4 is actually using Texture.Sample() syntax if I remember correctly. 
It probably has something to do with the way Unity cross-compiles HLSL to different languages. I would say it is a Unity bug but I have no way to verify. I don't have PS4 devkit. Can you try to use [this](https://github.com/SlightlyMad/VolumetricLights/commit/2e9e2a6650c19e1a406b4f5f3bc401cbca016a7a) commit? It still uses old syntax. Maybe it will compile...

**Comment by ypypjay** [comment]
Hi,SlightlyMad.Thanks for the reply.
I tried to use your commit.No luck.The 'BilateralBlur' shader still throws me 'undeclared identifier' errors when compiling.
Maybe it's a Unity shader convertion bug.I'll try to look into PSSL to find some clues.
I'll let you know when I find something.
Thanks again.

**Comment by SlightlyMad** [comment]
Did you use all files from the "2e9e2a6" revision or only the VolumetricLights script from the link I gave you? I'm asking because I had this misunderstanding with someone else couple days ago. And because I can't come up with something better.  Sorry, I'm afraid I won't be able to help you without devkit.
