### ISSUE TITLE
Effect disabling entirely when no shadows present near camera

### ISSUE THREAD

**Issue by AshkoreDracson** [SlightlyMad/VolumetricLights#5]
Hello!

I'm having an issue that to be quite frank i've been having virtually in all assets of volumetric lights, atmospheric scattering, height fog, global fog, volumetric fog etc...

The effect works great, however whenever there are no shadows being casted near the camera, the effect disables itself entirely.

[GIF of problem](http://i.imgur.com/lHPrhIt.gifv)

Just wanted to know if this is intended behaviour (and by extension intended behaviour of all volumetric effect assets), or if i'm just doing something terribly wrong or anything I might be missing for the proper scene setup, or maybe even if there's something wrong with my GPU drivers.

**Comment by SlightlyMad** [comment]
Yes, this is a known Unity issue (reported ages ago). Unity stops rendering shadows if there are no visible shadow casters. That's a good thing. But it also stops executing command buffers at that moment. This breaks the effect. There is no way how to detect it happened and so we can't do anything about it.

There is a simple workaround though. Place your camera inside a small shadow-casting 3d cube. The cube won't be visible from your camera because the back faces will be discarded by the rasterizer. This way there is a shadow-casting object in front of your camera at all times and Unity will be forced to keep updating shadows and executing our command buffers.
You could probably find a more elegant solution but the goal is always the same - force Unity to update shadows at all times. Hope this helps.

**Comment by AshkoreDracson** [comment]
Alright, good to know i'm not the only one haha! And many thanks for the workaround!
