### ISSUE TITLE
Camera Flip

### ISSUE THREAD

**Issue by Shtrude1** [SlightlyMad/VolumetricLights#6]
For some reason when i hit play camera flips 180 and mirrors the image horizontal
![1](https://cloud.githubusercontent.com/assets/24809623/21521865/f5cdf84c-cd00-11e6-853e-a2e5bd5a2d14.jpg)
![2](https://cloud.githubusercontent.com/assets/24809623/21521866/f5ce08f0-cd00-11e6-8e11-1c458b2d9c05.jpg)
![3](https://cloud.githubusercontent.com/assets/24809623/21521864/f5cd4758-cd00-11e6-9440-298e4f17b675.jpg)

This also happens on example scenes that VL provides

**Comment by Petethegoat** [comment]
Make sure your rendering path is set to deferred.

**Comment by SlightlyMad** [comment]
Actually, forward rendering path is supported for a month or two now. But it gave me an idea. If you can use forward path it means you can use MSAA too. It didn't occur to me when I added forward rendering path support. I didn't try it. So maybe MSAA is the problem here.

@Shtrude1  Make sure MSAA is disabled and let me know if it helps.

**Comment by Shtrude1** [comment]
I disabled MSAA and it worked fine with forward.All in all thanks for the info @Petethegoat , @SlightlyMad .

**Comment by SlightlyMad** [comment]
Good to know. I'll fix it and close the issue someday...

**Comment by Petethegoat** [comment]
@SlightlyMad Ah, neat. readme.md still says it has to be deferred+HDR. :)

**Comment by SlightlyMad** [comment]
> @SlightlyMad Ah, neat. readme.md still says it has to be deferred+HDR. :)

One part of the readme says it is required and another part says it is not. I've got all bases covered :)

**Comment by SlightlyMad** [comment]
Fixed
